### ISSUE TITLE
Dependency vulnerability 

### ISSUE THREAD

**Issue by delvedor** [davisjam/safe-regex#23]
Hello!
Your dependency `regexp-tree` has a security vulnerability, see https://snyk.io/test/github/fastify/fastify.
Can you update the dependency to a new (and safer) version?
Thanks! :)

**Comment by davisjam** [comment]
Will this be fixed by #22?

**Comment by delvedor** [comment]
Yes! :)

**Comment by davisjam** [comment]
Fixed in #22, published in v2.0.2.
