### ISSUE TITLE
Named capturing groups are not dangerous

### ISSUE THREAD

**Issue by xamgore** [davisjam/safe-regex#26]
* Returns false on `/(?<topics>test)/`
* If we remove `?<topics>`, then `/(test)/` returns true

Both are safe in essence.

**Comment by davisjam** [comment]
I'm having trouble reproducing this.

```
(10:14:40) jamie@woody /tmp/i $ cat t.js
const sr = require('safe-regex');
console.log(sr(/(?<topics>test)/));
console.log(sr(/(test)/));

(10:15:12) jamie@woody /tmp/i $ node --version
v12.7.0
(10:15:15) jamie@woody /tmp/i $ node t.js
true
true
```

**Comment by rarkins** [comment]
@ViceIce I think you have some examples too?

**Comment by ViceIce** [comment]
```js
/^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)(?<prerelease>[^.-]+)?(-(?<architecture>.*))?$/
```

**Comment by ViceIce** [comment]
@rarkins The problem aren't the named capture groups.

```js
/(a*)?/
```

We have nested repetitions.

**Comment by davisjam** [comment]
FWIW, nesting with ?s is not usually problematic. Hoping to fix that soon.

**Comment by xamgore** [comment]
I've been using [eslint-plugin-security](https://www.npmjs.com/package/eslint-plugin-security) `^1.4.0`, which in his turn uses safe-regex package `^2.0.0` ([line 28 in package.json](https://github.com/nodesecurity/eslint-plugin-security/blob/master/package.json#L28)).

<details><summary>Some screenshots of ESlint errors</summary>

* `/(?<topics>test)*/.test('a')` — the question mark makes the algorithm angry
   ![image](https://user-images.githubusercontent.com/4586392/63998531-007fd580-cb0a-11e9-8ebe-f7090d39bdae.png)
 

* `/(test?)*/.test('a')` — there is no the capturing group, but the question mark is left
   ![image](https://user-images.githubusercontent.com/4586392/63998603-26a57580-cb0a-11e9-8128-aeefb923f5d9.png)


* `/(test)*/.test('a')` — no issues
   ![image](https://user-images.githubusercontent.com/4586392/63998716-708e5b80-cb0a-11e9-8b70-872f90f44a68.png)

</details>

By the way, the oldest version of safe-regex in this repo is [`1.1.0`](https://github.com/davisjam/safe-regex/blob/master/package.json#L3), what is also weird.

**Comment by davisjam** [comment]
Thanks for the report. Currently traveling, will look soon.
