### ISSUE TITLE
is not detect ReDoS simple from wikipedia

### ISSUE THREAD

**Issue by magicode** [davisjam/safe-regex#45]
https://en.wikipedia.org/wiki/ReDoS
```js
/^(a|aa)+$/.test("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!");
```

**Comment by davisjam** [comment]
Such regexes are problematic, but out of scope for the "star height" heuristic used by this module at the moment.

See the algorithms underlying [vuln-regex-detector](https://github.com/davisjam/vuln-regex-detector) for an alternative.

**Comment by ChALkeR** [comment]
A simpler example would be `/a*a*b/`.
