### ISSUE TITLE
CI: Specify Node versions

### ISSUE THREAD

**Issue by davisjam** [davisjam/safe-regex#9]
Which version(s) should we explicitly test in Travis? Every Node that supports `const` and `let` I think.

**Comment by sverweij** [comment]
Is following node.js' [release schedule](https://nodejs.org/en/about/releases/) an idea?

At this date this'd mean node 8, 10 and 12 (all of which support `const` and `let`).

**Comment by davisjam** [comment]
8 is EOL soon, so 10 and 12 I guess.

I would be happy to merge a PR updating the Travis config file to target those Node versions.

I am not interested in running Travis on web browsers which used to be the practice for this project.

**Comment by sverweij** [comment]
I can contribute a working travis config - but you'll probably have to configure something in the `safe-regex` project settings to enable it b/c I didn't see it triggered in previous PR's to this repo...
